name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Build
        run: mvn -DskipTests -B clean package
        with:
          cache: 'maven'
      - name: Test
        run: mvn test
        with:
          cache: 'maven'
      - name: Sources
        run: mvn source:jar
        with:
          cache: 'maven'
      - name: Install
        run: mvn install
        with:
          cache: 'maven'
      - name: Javadoc
        run: mvn javadoc:jar
        with:
          cache: 'maven'
        