name: Build, Test, and Release

on:
  push:
    branches:
      - 'master'
      - 'develop'
      
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    env:
       GPG_TTY: $(tty)
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Build
        run: mvn -DskipTests -B clean package
      - name: Test
        run: mvn -B test
      - name: Sources
        run: mvn -B source:jar
      - name: Install
        run: mvn -B install
      - name: Javadoc
        run: mvn -B javadoc:jar
      - name: Publish to the Maven Central Repository
        run: mvn -B deploy
      